remove unnecessary stuff from config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -8,11 +8,6 @@ jobs:
     docker:
       # specify the version you desire here
       - image: circleci/node:12.6.0
-        # environment:
-        #   MYSQL_ROOT_PASSWORD: root
-        #   MYSQL_DATABASE: urbandiction
-        #   MYSQL_USER: student
-        #   MYSQL_PASSWORD: student
 
       # Specify service dependencies here if necessary
       # CircleCI maintains a library of pre-built images
@@ -24,35 +19,35 @@ jobs:
     steps:
       - checkout
 
-      - run:
-          name: Install things we need
-          command: |
-            sudo apt-get update
-            sudo apt-get install -y libzip-dev
-            sudo apt-get install -y zlib1g-dev libicu-dev g++
-            sudo apt-get install mysql-client
-            sudo apt-get -y install mysql-server
+      # - run:
+      #     name: Install things we need
+      #     command: |
+      #       sudo apt-get update
+      #       sudo apt-get install -y libzip-dev
+      #       sudo apt-get install -y zlib1g-dev libicu-dev g++
+      #       sudo apt-get install mysql-client
+      #       sudo apt-get -y install mysql-server
       # - run:
       #     name: Fix MySQL socket config
       #     command: |
       #       sudo sh -c "echo 'pdo_mysql.default_socket=/var/run/mysqld/mysqld.sock' > /usr/local/etc/php/conf.d/pdo.ini"
-      - run:
-          name: Start database server
-          command: |
-            sudo service mysql start
-            sleep 2
-            ps aux | grep mysql
-      - run:
-          # Our primary container isn't MYSQL so run a sleep command until it's ready.
-          name: Waiting for MySQL to be ready
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z 127.0.0.1 3306 && echo Success && exit 0
-              echo -n .
-              sleep 1
-            done
-            echo Failed waiting for MySQL && exit 1
+      # - run:
+      #     name: Start database server
+      #     command: |
+      #       sudo service mysql start
+      #       sleep 2
+      #       ps aux | grep mysql
+      # - run:
+      # Our primary container isn't MYSQL so run a sleep command until it's ready.
+      # name: Waiting for MySQL to be ready
+      # command: |
+      #   for i in `seq 1 10`;
+      #   do
+      #     nc -z 127.0.0.1 3306 && echo Success && exit 0
+      #     echo -n .
+      #     sleep 1
+      #   done
+      #   echo Failed waiting for MySQL && exit 1
       - run:
           name: Create non-admin user
           command: |
